<?php

return [
    'support_email' => 'info@jegvarazsbolt.hu',
    'support_phone' => '+36 (20) 778-9928',
    'company_name' => 'Cég neve',
    'company_address' => 'Cég címe',
    'company_address_maps_link' => null,
    'company_phone' => 'Cég telefonszáma',
    'company_appointment_email' => 'Cég időpontfoglalási email címe',
    'company_appointment_phone' => 'Cég időpontfoglalási telefonszáma',
    'company_vat_number' => 'Cég adószáma',
    'company_bank_account' => 'Cég bankszámlaszáma',
    'company_bank_name' => 'Cég bankja',
    'company_bank_swift' => 'Cég bank SWIFT kódja',
    'company_bank_iban' => 'Cég bank IBAN száma',
    'company_logo' => 'company_logo.png',
    'company_favicon' => 'company_favicon.png',
    'company_footer_text' => '© 2023 Cég neve. Minden jog fenntartva.',
    'social_facebook' => 'https://www.facebook.com/cégprofil',
    'social_instagram' => 'https://www.instagram.com/cégprofil',
    'social_twitter' => 'https://www.twitter.com/cégprofil',
    'social_linkedin' => 'https://www.linkedin.com/company/cégprofil',
    'social_youtube' => 'https://www.youtube.com/cégprofil',
    'social_tiktok' => 'https://www.tiktok.com/@cégprofil',
    'social_pinterest' => 'https://www.pinterest.com/cégprofil',
    'social_whatsapp' => 'https://wa.me/1234567890',
    'social_telegram' => 'https://t.me/cégprofil',
    'social_viber' => 'viber://chat?number=1234567890',
    'social_snapchat' => 'https://www.snapchat.com/add/cégprofil',
    'social_twitch' => 'https://www.twitch.tv/cégprofil',
    'header_message' => 'Ingyenes kiszállítás minden termékünkre!',
    'hero_top_title' => 'Jégvarázsbolt.hu',
    'hero_main_title' => 'Klímaberendezések és hőszivattyúk webáruháza',
    'hero_subtitle' => 'Ingyenes kiszállítás',
    'hero_button_text' => 'Vásárlás',
    'items_per_page' => '10',
    'maintenance_mode' => 'off',
    'maintenance_message' => 'A weboldal karbantartás alatt áll. Kérjük, látogasson vissza később.',
    'facebook_verify_token' => 'your-secret-token',
    'facebook_app_id' => 'xxxxxxxxxxxxxxx',
    'facebook_app_secret' => 'xxxxxxxxxxxxxxx',
    'facebook_page_token' => 'EAAB........',
    'facebook_page_id' => 'xxxxxxxxxxxxxxx',
];
