name: Deploy to Production via SFTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upload via SFTP
        uses: wangyucode/sftp-upload-action@v2.0.4
        with:
          host: ${{ secrets.SFTP_HOST }}
          port: 22
          user: ${{ secrets.SFTP_USERNAME }}
          pass: ${{ secrets.SFTP_PASSWORD }}
          localDir: './'
          remoteDir: '/projects/jegvarazs/laravel'
          args: '-R'  # Rekurzív feltöltés
