name: Deploy to Production via SFTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upload via SFTP
        uses: wangyucode/sftp-upload-action@v2.0.4
        with:
          host: ${{ secrets.SFTP_HOST }}
          port: 22
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          localDir: './'
          remoteDir: '/var/www/html/projects/jegvarazs/laravel'
          exclude: ".git,.DS_Store,**/node_modules" # Optional. exclude patterns (glob) like .gitignore, use ',' to split, Default to ''.

