name: Deploy to Production via SFTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, ctype, json, bcmath
          tools: composer

      - name: Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader --no-scripts

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Node.js dependencies
        run: npm ci

      - name: Build frontend assets
        run: npm run build

      #- name: Upload Laravel (excluding public)
      #  uses: wangyucode/sftp-upload-action@v2.0.4
      #  with:
      #    host: ${{ secrets.SFTP_HOST }}
      #    port: 22
      #    username: ${{ secrets.SFTP_USERNAME }}
      #    password: ${{ secrets.SFTP_PASSWORD }}
      #    localDir: './'
      #    remoteDir: '/var/www/html/projects/jegvarazs/laravel'
      #    exclude: ".git,.DS_Store,**/node_modules,public,tests,storage/*.key,storage/logs/*,vendor"

      #- name: Upload public folder separately (including build)
      #  uses: wangyucode/sftp-upload-action@v2.0.4
      #  with:
      #    host: ${{ secrets.SFTP_HOST }}
      #    port: 22
      #    username: ${{ secrets.SFTP_USERNAME }}
      #    password: ${{ secrets.SFTP_PASSWORD }}
      #    localDir: './public'
      #    remoteDir: '/var/www/html/projects/jegvarazs/public_html'
      #    exclude: ".DS_Store"

      - name: Upload Laravel to production server (excluding public)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.JEGVARAZS_PROD_FTP_HOST }}
          username: ${{ secrets.JEGVARAZS_PROD_FTP_USERNAME }}
          password: ${{ secrets.JEGVARAZS_PROD_FTP_PASSWORD }}
          server-dir: 'jegvarazsbolt.hu/laravel/'
          local-dir: './'
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            .DS_Store
            vendor/**
            public/**
            tests/**
            storage/**

      - name: Upload public folder separately (including build)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.JEGVARAZS_PROD_FTP_HOST }}
          username: ${{ secrets.JEGVARAZS_PROD_FTP_USERNAME }}
          password: ${{ secrets.JEGVARAZS_PROD_FTP_PASSWORD }}
          server-dir: 'jegvarazsbolt.hu/'
          local-dir: './public'
          exclude: |
            .DS_Store
